<a href="https://colab.research.google.com/github/Zkeera/machine-learning-dasar/blob/main/%5BKlasifikasi%5D_Submission_Akhir_BMLP_Mohammad_Taqi_Ashiddiqi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Penting**
- Pastikan Anda melakukan Run All sebelum mengirimkan submission untuk memastikan seluruh cell berjalan dengan baik.
- Hapus simbol pagar (#) jika Anda menerapkan kriteria tambahan
- Biarkan simbol pagar (#) jika Anda tidak menerapkan kriteria tambahan

# **1. Import Library**
Pada tahap ini, Anda perlu mengimpor beberapa pustaka (library) Python yang dibutuhkan untuk analisis data dan pembangunan model machine learning.

In [20]:
# Import library yang diperlukan
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, confusion_matrix
from joblib import dump

# **2. Memuat Dataset dari Hasil Clustering**
Memuat dataset hasil clustering dari file CSV ke dalam variabel DataFrame.

In [21]:
url = "https://raw.githubusercontent.com/Zkeera/machine-learning-dasar/refs/heads/main/dataset/data_clustering.csv"
df = pd.read_csv(url)

In [22]:
df.head()

Sex  Length  Diameter  Height  WholeWeight  ShuckedWeight  VisceraWeight  \
0    2   0.350     0.265   0.090       0.2255         0.0995         0.0485   
1    0   0.530     0.420   0.135       0.6770         0.2565         0.1415   
2    2   0.440     0.365   0.125       0.5160         0.2155         0.1140   
3    1   0.330     0.255   0.080       0.2050         0.0895         0.0395   
4    1   0.425     0.300   0.095       0.3515         0.1410         0.0775   

   ShellWeight  Age  Target  
0        0.070    7       2  
1        0.210    9       0  
2        0.155   10       0  
3        0.055    7       2  
4        0.120    8       2

# **3. Data Splitting**
Tahap Data Splitting bertujuan untuk memisahkan dataset menjadi dua bagian: data latih (training set) dan data uji (test set).

In [23]:
X = df.drop(columns=['Target'])
y = df['Target']

In [24]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [25]:
# Menampilkan ukuran data pelatihan dan pengujian
print(f"Data Pelatihan: {X_train.shape[0]} baris")
print(f"Data Pengujian: {X_test.shape[0]} baris")

Data Pelatihan: 3340 baris
Data Pengujian: 836 baris


# **4. Membangun Model Klasifikasi**
Setelah memilih algoritma klasifikasi yang sesuai, langkah selanjutnya adalah melatih model menggunakan data latih.

Berikut adalah rekomendasi tahapannya.
1. Menggunakan algoritma klasifikasi yaitu Decision Tree.
2. Latih model menggunakan data yang sudah dipisah.

In [26]:
model = DecisionTreeClassifier(random_state=42)

In [27]:
model.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)

In [28]:
# Menampilkan akurasi pada data pelatihan dan data pengujian
train_accuracy = model.score(X_train, y_train)
test_accuracy = model.score(X_test, y_test)

print(f"Akurasi pada data pelatihan: {train_accuracy:.4f}")
print(f"Akurasi pada data pengujian: {test_accuracy:.4f}")

Akurasi pada data pelatihan: 1.0000
Akurasi pada data pengujian: 0.9533


In [29]:
# Melakukan prediksi pada data pengujian
y_pred = model.predict(X_test)

In [30]:
# Menampilkan laporan klasifikasi
print("Laporan Klasifikasi:")
print(classification_report(y_test, y_pred))

Laporan Klasifikasi:
              precision    recall  f1-score   support

           0       0.96      0.92      0.94       243
           1       0.94      0.96      0.95       302
           2       0.97      0.99      0.98       171
           3       0.95      0.96      0.95       120

    accuracy                           0.95       836
   macro avg       0.96      0.96      0.96       836
weighted avg       0.95      0.95      0.95       836



In [31]:
# Menampilkan matriks kebingungannya
print("Matriks Kebingungannya:")
print(confusion_matrix(y_test, y_pred))

Matriks Kebingungannya:
[[224  14   5   0]
 [  7 289   0   6]
 [  2   0 169   0]
 [  0   5   0 115]]


In [32]:
# Menyimpan Model
import joblib
dump(model, 'decision_tree_model.h5')

['decision_tree_model.h5']

In [33]:
from google.colab import files

df.to_csv('data_klasifikasi.csv', index=False)
files.download('data_klasifikasi.csv')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

# **5. Memenuhi Kriteria Skilled dan Advanced dalam Membangun Model Klasifikasi**



**Biarkan kosong jika tidak menerapkan kriteria skilled atau advanced**

In [34]:
# Melatih model menggunakan algoritma klasifikasi selain Decision Tree.

In [35]:
# Menampilkan hasil evaluasi akurasi, presisi, recall, dan F1-Score pada seluruh algoritma yang sudah dibuat.

In [36]:
# Menyimpan Model Selain Decision Tree
# Model ini bisa lebih dari satu
# import joblib
# joblib.dump(___, 'explore_<Nama Algoritma>_classification.h5')

Hyperparameter Tuning Model

Pilih salah satu algoritma yang ingin Anda tuning

In [37]:
# Lakukan Hyperparameter Tuning dan Latih ulang.

In [38]:
# Menampilkan hasil evaluasi akurasi, presisi, recall, dan F1-Score pada algoritma yang sudah dituning.

In [39]:
# Menyimpan Model hasil tuning
# import joblib
# joblib.dump(model_dt, 'tuning_classification.h5')